package apanel::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'db::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:my.db',
        user => '',
        password => '',
    }
);

=head1 NAME

apanel::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<apanel>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<db::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

Ynon Perek

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
